# Generated by Django 4.0.6 on 2022-07-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamtracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcrsquestion',
            name='active',
            field=models.BooleanField(verbose_name='Is this question currently active?'),
        ),
    ]
