# Generated by Django 4.0.6 on 2022-07-20 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamtracking', '0002_alter_tcrsquestion_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcrsquestionresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teamtracking.tcrsquestion'),
        ),
    ]
