# Generated by Django 4.0.6 on 2022-07-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamtracking', '0003_alter_tcrsquestionresponse_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcrsresponse',
            name='iteration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
