# Generated by Django 4.0.6 on 2022-07-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teamtracking", "0004_tcrsresponse_iteration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tcrsresponse",
            name="iteration",
            field=models.CharField(max_length=5),
        ),
    ]
