# Generated by Django 4.0.6 on 2022-07-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teamtracking", "0005_alter_tcrsresponse_iteration"),
    ]

    operations = [
        migrations.AddField(
            model_name="tcrsresponse",
            name="score",
            field=models.IntegerField(default=-500),
            preserve_default=False,
        ),
    ]
