# Generated by Django 4.0.6 on 2022-07-27 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teamtracking", "0007_iteration_alter_tcrsresponse_iteration"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="course",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="note",
            name="note_text",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="note",
            name="section",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="note",
            name="submit_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Note date"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="note",
            name="submitter",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submitter",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="note",
            name="team",
            field=models.CharField(
                default="",
                max_length=20,
                verbose_name="Name or number of the student's team",
            ),
            preserve_default=False,
        ),
    ]
