# Generated by Django 4.0.6 on 2022-07-28 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teamtracking", "0008_note_course_note_note_text_note_section_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="course",
        ),
        migrations.RemoveField(
            model_name="note",
            name="section",
        ),
        migrations.RemoveField(
            model_name="tcrsresponse",
            name="course",
        ),
        migrations.RemoveField(
            model_name="tcrsresponse",
            name="section",
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course", models.CharField(max_length=10)),
                ("section", models.CharField(max_length=10)),
                (
                    "team",
                    models.CharField(
                        max_length=20,
                        verbose_name="Name or number of the student's team",
                    ),
                ),
                (
                    "assigned_TA",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitter",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="note",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="team",
                to="teamtracking.team",
            ),
        ),
        migrations.AlterField(
            model_name="tcrsresponse",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="team",
                to="teamtracking.team",
            ),
        ),
    ]
