# Generated by Django 4.0.6 on 2022-07-28 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teamtracking", "0009_remove_note_course_remove_note_section_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="note",
                to="teamtracking.team",
            ),
        ),
        migrations.AlterField(
            model_name="tcrsresponse",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="response",
                to="teamtracking.team",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="assigned_TA",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_TA",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
